project:
  type: website
  output-dir: docs

website:
  title: "Computational Contemplative-Neuroscience"
  favicon: erp.jpg
  
  page-footer:
    left: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
    right: |
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/usman-afzali/PSYC480)</span>
    background: "#543391"
  
  search: 
    location: navbar
    type: textbox
  navbar:
    pinned: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: intro.qmd
      - text: "Classes"
        file: presentations.qmd            
      - text: "Labs"
        file: labs.qmd
      - text: "Course Outline"
        file: outline.qmd
      - text: "Assessments"
        file: assessments.qmd
      - text: "How to Use?"
        file: how-to-use.qmd        
    right:
      - icon: github
        href: https://github.com/usman-afzali/psyc344

    page-navigation: true

format:
  html:
    theme: pulse
    css: styles.scss
    highlight-style: espresso
    code-tools: false
    code-block-bg: true
    citations-hover: true

editor: source
