---
title: "Course Outline and Topics"
listing:
  id: intro-listings
  image-align: right
  contents: intro
  sort: "title asc"
  type: default
  categories: false
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: false
---

## Whakamahuki | Description

PSYC480 is a one semester 15-point (0.1250 EFT) course aimed at postgraduate students who are interested in gaining skills in computational neuroscience. As neuroscience knowledge grows in its scope of societal applications, so does the need to educate a wider audience on how to critically evaluate its research findings. Recent years have seen numerous initiatives to reach a wider university population by making neuroscience more interdisciplinary, integrative, accessible and applicable to students’ lives and intrinsic interests. In addition, we see an increasing global trend in adopting embodied, embedded, enacted, and extended research of cognitive processes (also known as the 4E approach), rather than sufficing with behavioural-only lab studies. The focus of the course will be to apply computational neuroscience techniques to the emerging field of research that aims to understand changes within the mind, brain, and body as a result of contemplative practices, such as mindfulness-based meditation, contemplative walking, or yoga. More broadly, practices where the subjective sense of oneself as an isolated entity can temporarily fade into an experience of unity with other people or one's surroundings. The course is interdisciplinary and attempts to clarify such mind-brain-body changes across emotional, behavioural, cognitive, and perceptual domains with an emphasis for relating such changes to data obtained with Electroencephalogram (EEG) and analysed with the latest computational techniques. Hence, PSYC480 will also be a step towards adopting the 4E approach to cognition.

The goal of this course is to teach computational neuroscience and data science relevant for obtaining neurological data from people using static and portable EEG devices, understand the characteristics of such data sets, develop an understanding of the anatomical structures, physiological, and pathological states of the brain and spinal cord and nerves in various states, and analyse such data sets. At the end of the course, the students will gain an understanding of:

-   Structure and function of the brain and neurological processes.
-   Psychological and mental health attributes that can be understood and analyzed using electrophysiological signals.
-   Be able to understand to design and carry out experiments to obtain EEG signals.
-   Be able to analyze EEG signals and apply computational tools to derive appropriate statistical measures from brain rhythm data, such as micro-states.



## Hua Akoranga | Learning Outcomes

The objectives of the course are:

-   The student will recognise and describe the anatomical structure and function of the brain and neurological processes and be able to identify the role and function of the different brain regions (frontal, temporal, parietal, and occipital).
-   The student will describe the physiological processes in the brain and neural systems (nerve conduction pathways).
-   The student will identify and report the neurological correlates of the various states (such as calmness, agitation, pathological states, stroke, muscle movements).
-   The student will analyse how cultural factors and neurophysiological process act with each other, e.g., with the Māori, Pasifika, and other ethnic groups.
-   The student will explain various psychological and mental health processes as related to experiences that elicit self-transcendent states.
-   The student will define the physics of electroencephalographic signal processing.
-   The student will analyse EEG signals using portable and non-portable devices and understand how such data are used and processed.
-   The student will report processing of EEG signals using Matlab (and other tools such as EEGlab), and/or with other software tools such as MNE (Python) and Neuroconductor suite of packages.

## Prerequisites:

BSc (PSYC) or BA (PSYC) or BDataSc or BHSc

## Aromatawai | Assessment

| Assessment | Due | % of final mark |
|---------|:-----|------:|
| Written labs      | Due Fridays   |    20%  |
| Class participation    | During lectures  |   10% |
| Lit Review/Essay      | 17 Mar   |     10%  |
| Oral group presentation | Week 10 (15 May) | 20% |
| Lab Report | 2 Jun | 40% |

**Tuhinga | Textbooks and Readings**

There are no required textbooks for this course. Assigned readings for lectures/labs will be provided online via LEARN.

**Wātaka | Timetable**


| Day	      | Time   |    Location  |
|---------|:-----|------:|
| Monday (Lecture)    | 10am – 12pm  |   Beatrice Tinsley 111 |
| Wednesday (Lab)     | 3pm – 4pm   |    Psyc/Soc 225 |


*Please check Course Information System and/or My Timetable for any possible changes to day/time/venue.*


**Wātaka | Timetable**

Summary of Course Content

| Week | Lecture topic | Lab/tutorial Topic |
|---------|:-----|------:|
| Week 1     | Introductions Fundamentals of Neuroscience |  Lab 1: Introduction to MATLAB/EEGLAB, Importing EEG data to EEGLAB, importing event markers and channel locations |
| Week 2      | Methods in Neuroscience     | Lab 2: referencing and filtering |
| Week 3      | Fundamentals of Electroencephalography (EEG)    |     Lab 3: Examining raw data and identifying bad channels, automatic and manual rejection of bad channels | 
| Week 4     | EEG Data Analysis: Principles of Digital Signal Processing   |    Lab 4: Independent component analysis, labelling bad components for rejection, and rejecting bad components | 
| Week 5     | Self-Transcendent (contemplative) science 1  |    Lab 5: Extracting brain rhythms & obtaining micro-states |
| Week 6     | Self-Transcendent (contemplative) science 2  |    Lab 6: Processing many datasets together – or creating a “study” |
| Week 7     | Wider applications of neuroscience: Brain computer interfaces and neurofeedback   |    Lab 7: Obtaining EEG from a subject immersed in contemplative activity  |
| Week 8     | Wider applications of neuroscience: Brain Fingerprinting   |    Lab 8: Statistical operations |
| Week 9     | Reproducibility in neuroscience   |    Lab 9: Analysing and interpretation of data |
| Week 10     | Group Presentations  |    Lab 10: Report Writing |
| Week 11    | Broadening the scope: 4E Cognition  | |
| Week 12    | Guest Lecture (TBC) |  |

*Lecturers and topics subjected to changes during the semester.*


**Ngā Whakamāramatanga | General Course Information for Psychology**

**Te Ratonga Tautoko Hangarau | IT Services:** [https://www.canterbury.ac.nz/its/](https://www.canterbury.ac.nz/its/)

**AKO | LEARN** [https://learn.canterbury.ac.nz/](https://learn.canterbury.ac.nz/)

**UC Library Subject Guide:** [http://canterbury.libguides.com/psyc](http://canterbury.libguides.com/psyc)

**Te Tatū I Ngā Āwangawanga Ākonga | Addressing Student Concerns **

If you have any concerns about a course, please contact the Course Coordinator in the first instance. The School of Psychology, Speech and Hearing has a Psychology Staff/Student Liaison Committee and at least five students voluntarily represent postgraduate students for both papers and thesis years for the whole year. A request for volunteers is sent early in the first semester.

**Te Ratonga Whaikaha | Student Accessibility Service**

Please refer to [Te Ratonga Whaikaha | Student Accessibility Service | University of Canterbury](https://www.canterbury.ac.nz/accessibility/) for information on study support services.

**Test and Exam Special Arrangements for students registered with TRW | SAS**
Special arrangements for tests and examinations are generally organised, if required, at the beginning of the academic year, in collaboration with an Accessibility Advisor. Special arrangements have cut-off dates for each exam period, and you must be registered with TRW | SAS in advance if you require this support. While the implementation of special arrangements for exams are automatically arranged by the Examinations Office, you must email [examinations@canterbury.ac.nz](mailto:examinations@canterbury.ac.nz) to organise your special arrangements for tests.

**Mana Wānanga | Academic Integrity**

It is the responsibility of each student to be familiar with the definitions, policies and procedures concerning academic misconduct/dishonest behaviour. Instances of academic misconduct will be dealt with in a serious and appropriate manner. Students should refer to: [Academic Integrity | University of Canterbury](https://www.canterbury.ac.nz/about/ako/academic-quality/academic-integrity/)

**Tārua Whānako | Policy on Dishonest Practice**

Plagiarism, collusion, copying and ghost writing are unacceptable and dishonest practices.

-   Plagiarism is the presentation of any material (text, data, figures or drawings, on any medium including computer files) from any other source without clear and adequate acknowledgement of the source.
-   Collusion is the presentation of work performed in conjunction with another person or persons, but submitted as if it has been completed only by the named author(s).
-   Copying is the use of material (in any medium, including computer files) produced by another person(s) with or without their knowledge and approval.
-   Ghost writing is the use of another person(s) (with or without payment) to prepare all or part of an item submitted for assessment.

In cases where dishonest practice is involved in tests or other work submitted for credit, the student will be referred to the University Proctor. The instructor may choose to not mark the work.

The School of Psychology, Speech and Hearing reserves the right to require work to be submitted in electronic format so that it can be submitted to plagiarism detection websites.

**Ngā Tōmuringa | Late Work / Penalty**

Lab participation and lecture participation are designed to break down learning into ‘digestible’ chunks. As such, participation in labs and lectures are due at the end of their respective weeks; late participation will not be accepted. Late lab reports and individual lab reports will be marked down by 5% of the total score for each day it is late (i.e., reduced by 5% for being 1 day late, 10% for being 2 days late, etc.). 

If illness or special circumstances prevent you from submitting an assignment on time, this work should be accompanied by a medical certificate and/or a short note explaining why it is late. Days late include weekends and holidays. 

**Ngā Pairuri Motuhake | Special Consideration**

Special Consideration for assessments is for students who have covered the work of a course but have been prevented from demonstrating their knowledge or skills at the time of the assessment due to unforeseen circumstances. Students should consult the Special Considerations website for information:  [https://www.canterbury.ac.nz/study/special-consideration/](https://www.canterbury.ac.nz/study/special-consideration/).

Also on the Examinations webpage is information about Results and Appeals for final grades. The School of Psychology Speech and Hearing policy of “substantial part of assessment” for all courses is set at 50% of all coursework. Unless a minimum of 50% of coursework is completed, final special consideration will not be given. Additionally, special considerations in the form of aegrotats can only be applied to a maximum of 50% of coursework within a given course.

A special consideration application is **not the process to apply for an extension of time** to complete a piece of assessment. You must contact the course coordinator, with your supporting documentation, to apply for an extension of time to complete the assessment. Please note that where possible, an extension of time should be applied for prior to making an application for a special consideration e.g., for essays, literature reviews, or other written or ‘take-home’ assignments.

**Taumata Ako | Marks and Grades**

You will get a mark and/or a grade for each piece of assessment during the course and a final grade at the end of the course. For more information on the University regulations for credit see: [General conditions for credit regulations | General regulations | Regulations | University of Canterbury](https://www.canterbury.ac.nz/regulations/general-regulations/general-conditions-for-credit-regulations/).

**Te Pīra Taumata | Reconsideration of Grades**
Students can appeal any decision made on their final grade, and should, in the first instance, speak to the course coordinator about their grade. Students can apply through Student Services to appeal for up to four weeks after the release of results: [Result dates and appeals | Study | University of Canterbury](https://www.canterbury.ac.nz/study/examinations/result-dates-and-appeals/).

For more information see General Course and Examination Regulations in the University Calendar: [https://www.canterbury.ac.nz/publications/brochure-gallery/tabs/study-options/documents/UC-Calendar.pdf](https://www.canterbury.ac.nz/publications/brochure-gallery/tabs/study-options/documents/UC-Calendar.pdf)

**Ngā Ritenga Nawe | Complaints and Grievances**
If a student encounters any problems regarding any aspect of the course, they should in the first instance approach the lecturer concerned. Failing that, they can approach the course coordinator. For more information, please see the [Psychology Handbook](https://www.canterbury.ac.nz/science/schools/psyc-speech-hear/undergraduate-study/accordion-1/brochures/Psychology-Handbook-2020-Web.pdf).

**Te Matangaro i ngā Whakamātautau | Missed Tests**

In rare cases a student will not be able to sit a test. In such cases, the student should consult with the course coordinator to discuss if alternative arrangements are available. *This must be done well in advance of the set date of the test.* The criteria used for approving a special sitting are the same as the UC policy used for end-of-semester examinations, which are outlined below:

-   Clash with another test from other UC courses
-   Religious (Conflicting religious day or event)
-   Bereavement (family member or close friend)
-   Study (overseas study, must be a tertiary institute)
-   Sporting or cultural event (Representing NZ, Canterbury or the University of Canterbury)
-   Wedding (immediate family member or part of a bridal party)
-   Business (travel)

With the exception of the above criteria, tests will only be given at the regularly scheduled time and place. Missed tests will result in a score of 0% for that test.

**Ngā Whakamarumaru | Emergency Preparedness**

Please refer to this link to familiarise yourself with the information in the event of an emergency situation: [Emergency preparedness | University of Canterbury](https://www.canterbury.ac.nz/support/emergency/emergency-preparedness/)


----------------------------------------------------------------------------------