---
title: "The neuroscience of contemplation - 2"
subtitle: "PSYC480"
author: "Usman Afzali"
institute: "University of Canterbury"
date: 2023 03 27
format: 
  revealjs:
    theme: simple
    highlight-style: github
    slide-number: c/t
---

## Karakia Whakatūwhera {background-color=#346bc8}

::: {layout="[[50, 50], [100]]"}

Whakataka te hau ki te uru/
Whakataka te hau ki te tonga/
Kia mākinakina ki uta/
Kia mātaratara ki tai/
E hī ake ana te atakura/
He tio, he huka, he hau hū/
Tīhei mauri ora!

Cease the winds from the west/
Cease the winds from the south/
Let the breeze blow over the land/
Let the breeze blow over the ocean/
Let the red-tipped dawn come with a sharpened air./
A touch of frost, a promise of a glorious day.

:::


# Kauhau {background-color=orange}

-   Keeping up with Delorme
-   The neuroscience of self transcendent/contemplative practices

## Keeping up with Delorme {background-color=#346bc8}

-   [Process EEG data in MNE then build an automated pipeline](https://youtu.be/31N8WHioQ3U)
-   [Process EEG data then build a pipeline in EEGLAB](https://youtu.be/yaA1wq2nSIc)
-   [Process EEG data on the San Diego supercomputer (for free) in 10 minutes](https://www.youtube.com/watch?v=1_h8NFS_ipI&list=WL&index=30)


## Korero {background-color=#346bc8}

::: incremental

-   What does contemplation mean to you?
-   Braboszcz et al. (2017)
-   Yaden et al. (2017)
-   Nash et al. (2022). Resting-state networks of believers and non-believers: An EEG microstate study
-   Nash et al. (2022). Anxiety disrupts performance monitoring: integrating behavioral, event-related potential, EEG microstate, and sLORETA evidence

:::

## Karakia Whakatūwhera {background-color=#346bc8}

::: {layout="[[50, 50], [100]]"}

Unuhia, unuhia/
Te pou, te pou/
Kia wātea, kia wātea/
Āe, kua wātea


Remove, uplift/
The posts/
In order to be free/
Yes, it has been cleared/

:::


# THE END {background-color=orange}