---
title: "Reproducibility in neuroscience"
subtitle: "PSYC480"
author: "Usman Afzali"
institute: "University of Canterbury"
date: 2023 05 08
format: 
  revealjs:
    theme: simple
    highlight-style: github
    slide-number: c/t
---

## Karakia Whakatūwhera {background-color=#346bc8}

::: {layout="[[50, 50], [100]]"}

Whakataka te hau ki te uru/
Whakataka te hau ki te tonga/
Kia mākinakina ki uta/
Kia mātaratara ki tai/
E hī ake ana te atakura/
He tio, he huka, he hau hū/
Tīhei mauri ora!

Cease the winds from the west/
Cease the winds from the south/
Let the breeze blow over the land/
Let the breeze blow over the ocean/
Let the red-tipped dawn come with a sharpened air./
A touch of frost, a promise of a glorious day.

:::


# Kauhau {background-color=orange}

-   Housekeeping
-   Kōrero

## Housekeeping {background-color=#346bc8}

::: incremental

-   Data collection
-   Presentation topics - due this Friday

:::

## Kōrero {background-color=#346bc8}

::: incremental

-   Wingen (2022)
-   Haig (2022)
-   Jenkinson 92021)
-   Milkowski et al. (2018)
-   Marek et al. (2022)

:::

## Karakia Whakatūwhera {background-color=#346bc8}

::: {layout="[[50, 50], [100]]"}

Unuhia, unuhia/
Te pou, te pou/
Kia wātea, kia wātea/
Āe, kua wātea


Remove, uplift/
The posts/
In order to be free/
Yes, it has been cleared/

:::


# THE END {background-color=orange}