---
title: "4E Cognition"
subtitle: "PSYC480"
author: "Usman Afzali"
institute: "University of Canterbury"
date: 2023 05 22
format: 
  revealjs:
    theme: simple
    highlight-style: github
    slide-number: c/t
---

## Karakia Whakatūwhera {background-color=#346bc8}

::: {layout="[[50, 50], [100]]"}

Whakataka te hau ki te uru/
Whakataka te hau ki te tonga/
Kia mākinakina ki uta/
Kia mātaratara ki tai/
E hī ake ana te atakura/
He tio, he huka, he hau hū/
Tīhei mauri ora!

Cease the winds from the west/
Cease the winds from the south/
Let the breeze blow over the land/
Let the breeze blow over the ocean/
Let the red-tipped dawn come with a sharpened air./
A touch of frost, a promise of a glorious day.

:::


# Kauhau {background-color=orange}

-   Housekeeping
-   Kendal's presentation: 10:05-10:20
-   Kōrero

## Housekeeping {background-color=#346bc8}

::: incremental

-   Well done on figuring MS!
-   Guest lecture next week
-   Data collection

:::

## Kōrero {background-color=#346bc8}

::: incremental

-   Why 4E and MoBI: Usman - 10:20 - 10:25
-   Parada and Rossi (2020): Daniela, Sheena, Charlie, and Cambria - 10:25 - 10:40
-   Ladouce et al. (2022): Peer, Azadeh, Lucas, Charlie, and Cambria - 10:40 - 10:55
-   Break - 10:55 - 11:00
-   Jungnickel et al. (2019): Daniela, Sheena, Harriet, and Priya - 11:00 - 11:15


:::

## Kōrero {background-color=#346bc8}

::: incremental

-   Jungnickel and Gramann (2016): Peer, Azadeh, Lucas, Jasmine, and Kendal - 11:15 - 11:30
-   Grasso-Cladera et al. (2022): Harriet, Priya, Jasmine, and Kendal - 11:30 - 11:45
-   Conclusion: 11:45 - 11:50

:::

## Karakia Whakatūwhera {background-color=#346bc8}

::: {layout="[[50, 50], [100]]"}

Unuhia, unuhia/
Te pou, te pou/
Kia wātea, kia wātea/
Āe, kua wātea


Remove, uplift/
The posts/
In order to be free/
Yes, it has been cleared/

:::


# THE END {background-color=orange}