---
title: "Course Outline and Topics"
listing:
  id: intro-listings
  image-align: right
  contents: intro
  sort: "title asc"
  type: default
  categories: false
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: false
---

## Whakamahuki | Description

This intermediate course in research methods and statistics will guide you through the key steps of conducting psychological research that ultimately benefits and influences society. The lectures will cover a selection of topics on designing a project with consideration of research ethics, analysing and interpreting psychology data with rigour, and disseminating research findings for impact. The laboratory classes and assessments provide further experience in designing psychological research and writing up research in standard APA-style format.

## Prerequisites:
PSYC206

## Hua Akoranga | Learning Outcomes

-   Apply knowledge of research methods in designing a psychology research study involving human participants. 
-   Apply knowledge of research methods in designing a psychology research study involving human participants.
-   Recommend qualitative and mixed methods when appropriate for enriching research design.
-   Apply existing statistical knowledge (*t*-test, ANOVAs) in intermediate statistical analyses (factorial and repeated measures ANOVAs, moderated and mediated regression), and clearly and accurately report the results, adhering to APA standards.
-   Demonstrate professional standards for research integrity in Aotearoa New Zealand, including ethical treatment of participants, consideration of Mātauranga Māori in research, honest scholarship, and transparent communications.
-   Exercise and adapt strategies for working in a diverse research team, including efficient project coordination, routine communication, delegation of work to strengths, and building team cohesion through shared challenges, understanding, and successes.

## Aromatawai | Assessment

| Assessment | Due | % of final mark |
|---------|:-----|------:|
| Weekly Quizzes      | Due Sundays, 11:59pm at the end of the week   |    5%  |
| Learning Activities     | Weeks 1, 3, 5, 6, 7, 8, and 12; Due Sundays, 11:59pm at the end of the week  |   5% |
| Lab Exercises      | Weeks 2, 4, 7, 8, 9, 10; Due Sundays, 11:59pm at the end of the week    |     10%  |
| Teamwork Process (related to the Group Assignment) | Weeks 1, 2, 4; Due Sundays, 11:59pm at the end of the week | 5% |
| Group Assignment: Putting together a Human Research Ethics Application + Māori consultation | Friday, 23 Dec, 11.59pm | 20% |
| Lab Report: Conducting and reporting analyses APA-style | Sunday, 5 Feb, 11.59pm | 25% |
| Final Exam | 2-hour multiple choice and short answers, 13 Feb, from 10am to 12pm | 30% |

You will be able to choose one other group member from your own lab stream for the Group Assignment that will be completed by groups of two students each. A peer-marking scheme will be used to ensure fairness in individual grades; your project grades will be a percentage of your input as a group member (as rated by your group member). For the Lab Report, you will be able to complete it on your own.

Reports will be due at 11.59pm on the designated due date, and must be submitted electronically through the online portal on LEARN. Hard copies of reports are not required.

*Late Work:* Lab participation and lecture participation are designed to break down your learning into ‘digestible’ chunks. As such, participation in labs and lectures are due at the end of their respective weeks; late participation will not be accepted. Late group lab reports and individual lab reports will be marked down by 5% of the total score for each day it is late (i.e., reduced by 5% for being 1 day late, 10% for being 2 days late, etc).

If you require an extension for a piece of assessment, please contact Usman or the online facilitators with your request at least two working days before the assessment is due.

**Tuhinga | Textbooks and Readings**

Please note that the range of topics covered in PSYC344 could not possibly be covered in a single textbook. Therefore, below are two free resources that encompass a major part of the required text. Yet again, some further required readings will also be suggested, generally from published articles and reliable sources, where applicable.

**Required Text (Free/Open Access):**

1. Navarro, D. J., and Foxcroft, D. R. (2022). Learning statistics with jamovi: A tutorial for psychology students and other beginners. (Version 0.75). DOI: 10.24384/hgc3-7p15 Available from [here](
http://learnstatswithjamovi.com).

2. Gelman, A., Hill, J., and Vehtari, A. (2022). Regression and other stories. Cambridge University Press. Free legal download (for personal use only) available from [here](https://avehtari.github.io/ROS-Examples/). [click ROS online PDF]

3. Some articles will also be provided as required readings during the semester.

You are expected to read all required readings for lectures, preferably prior to attending lectures. All required readings will be examinable unless otherwise specified by the lecturer.

**Recommended Text (Available from UC Library)**

The book below is not a required text and will not be examined. However, it clarifies some of the topics in an accessible manner and provides further insights to various topics covered in PSYC344 that might be helpful to those who plan on postgraduate studies in psychology. It may be borrowed from the UC Library for a limited amount of time.

1. Jackson, S. L. (2016). [Research Methods and Statistics, A critical thinking approach (5th ed.)](https://go.exlibris.link/j1YVPdnB). Cengage.

2. Field, A. (2018). [Discovering statistics using IBM SPSS (5th ed.)](https://go.exlibris.link/9vD0C9J9). Sage.

**Course Material and Information**

All course material, lecture notes and information about the course will be available on the university website known as **LEARN**. You can access this website with the following link: [http://www.learn.canterbury.ac.nz/](http://www.learn.canterbury.ac.nz/)

**Wātaka | Timetable**

Pre-recorded weekly lectures will be available each Monday at 9am.

| Week | Dates | Topic | Lab |
|---------|:-----|------:|------:|
| Week 0     |   |    Course Preparation | |
| Week 1     | Nov 14  |   Welcome to PSYC344: Expectations and fundamentals, Scientific writing | |
| Week 2      | Nov 21    |     Participant considerations: Ethics, recruitment, and research relationships | Lab 1: Building blocks for group work (Group Assignment introduction) |
| Week 3      | Nov 28    |     Philosophy of science: The nature of scientific inquiry and its use in psychology | Lab 2: Group Assignment Tutorial |
| Week 4     | Dec 5   |     Measurement: Validity and reliability, Scale development | Lab 3: Descriptives, visualization, & Cleaning datasetsl |
| Week 5     | Dec 12   |    Measurement: Factor analysis and scale validation |  |
| Week 6     | Dec 19   |    Causal inference in psychology | Group Assignment due Dec 23, 2022, at 11.59pm |
| Week 7     | Jan 5   |    Parametric and non-parametric tests of comparing two means: *t*-tests and alternatives | Lab 4: Scale Validation and EFA, Tutorial 2: Lab Report Introduction |
| Week 8     | Jan 9   |    ANOVA and non-parametric alternatives | Lab 5: Null hypothesis significance testing |
| Week 9     | Jan 16   |    Regression: bivariate, multiple, and logistic | Lab 6: ANOVA |
| Week 10     | Jan 23   |    Qualitative research and mixed methods | Lab 7: Regression |
| Week 11    | Jan 30  |    Recent advances and issues: Open-science, pre-registrations, replication crisis, robust statistics, The New Statistics | Lab Report due 5 Feb 2023 at 11.59pm |
| Week 12    | Feb 6  |    Science communication and impact |  |

**Online Laboratory Tutorials**

Labs commence during the **second week** of the semester (the week starting Nov 21st). 
Recording tutorials of lab exercises will be provided to you on a weekly basis. Please ensure to try working out exercises before you watch the video, as it is more effective to learn by doing. The lab activities are designed to provide you with hands-on applied learning of the topics covered in the lectures. Finding answers to the lab exercises will not only counts towards your final grade in the course, but will also provide you with the knowledge and skills for completing lab reports.

Please note that you will need to have jamovi installed on your device to complete the labs. You can also install the Office 365 package to write your assignments and access your emails. 

Both of these are freely available to students, through the following links:

Office 365 install instructions for UC students: [https://www.canterbury.ac.nz/its/knowledge-base/office-365/](https://www.canterbury.ac.nz/its/knowledge-base/office-365/)

jamovi download: [https://www.jamovi.org/download.html](https://www.jamovi.org/download.html)

APA guide: [https://apastyle.apa.org/instructional-aids/tutorials-webinars](https://apastyle.apa.org/instructional-aids/tutorials-webinars)

**Zui**
Each member of the teaching team will be holding at least one Zui (Zoom Hui) on a weekly basis. You can turn up to as many of these as you want. They can be used for lecture-related, lab-related, or assignment-related questions; and for any PSYC344-related issue for that matter. Times to be advised on Learn.

**Ngā Whakamāramatanga | General Course Information for Psychology**

**Te Ratonga Tautoko Hangarau | IT Services:** [https://www.canterbury.ac.nz/its/](https://www.canterbury.ac.nz/its/)

**AKO | LEARN** [https://learn.canterbury.ac.nz/](https://learn.canterbury.ac.nz/)

**UC Library Subject Guide:** [http://canterbury.libguides.com/psyc](http://canterbury.libguides.com/psyc)

**Te Tatū I Ngā Āwangawanga Ākonga | Addressing Student Concerns **

If you have any concerns about a course, please contact the Course Coordinator in the first instance. The School of Psychology, Speech and Hearing has a Psychology Staff/Student Liaison Committee and at least five students voluntarily represent postgraduate students for both papers and thesis years for the whole year. A request for volunteers is sent early in the first semester.

**Te Ratonga Whaikaha | Student Accessibility Service**

Please refer to [Te Ratonga Whaikaha | Student Accessibility Service | University of Canterbury](https://www.canterbury.ac.nz/accessibility/) for information on study support services.

**Tārua Whānako | Policy on Dishonest Practice**

Plagiarism, collusion, copying and ghost writing are unacceptable and dishonest practices.

-   Plagiarism is the presentation of any material (text, data, figures or drawings, on any medium including computer files) from any other source without clear and adequate acknowledgement of the source.
-   Collusion is the presentation of work performed in conjunction with another person or persons, but submitted as if it has been completed only by the named author(s).
-   Copying is the use of material (in any medium, including computer files) produced by another person(s) with or without their knowledge and approval.
-   Ghost writing is the use of another person(s) (with or without payment) to prepare all or part of an item submitted for assessment.

In cases where dishonest practice is involved in tests or other work submitted for credit, the student will be referred to the University Proctor. The instructor may choose to not mark the work.

The School of Psychology, Speech and Hearing reserves the right to require work to be submitted in electronic format so that it can be submitted to plagiarism detection websites.

**Ngā Pairuri Motuhake | Special Consideration**

Special Consideration for assessments is for students who have covered the work of a course but have been prevented from demonstrating their knowledge or skills at the time of the assessment due to unforeseen circumstances. Students should consult the Special Considerations website for information, and contact them directly with any queries. [https://www.canterbury.ac.nz/study/special-consideration/](https://www.canterbury.ac.nz/study/special-consideration/).

Also on the Examinations webpage is information about Results and Appeals for final grades. The School of Psychology Speech and Hearing policy of “substantial part of assessment” for all courses is set at 50% of all coursework. Unless a minimum of 50% of coursework is completed, final special consideration will not be given.

The UC Special Considerations Team will no longer accept Special Consideration applications for essays/assignments or quizzes where the student is wishing to seek an extension. These will be immediately declined and the student referred to the respective course coordinator. All extension applications should be made, with the relevant supporting documentation, directly to the course coordinator, with the decision being conveyed to the student by the course coordinator.

**Taumata Ako | Marks and Grades**

You will get a mark and/or a grade for each piece of assessment during the course and a final grade at the end of the course. For more information on the University regulations for credit see: [https://www.canterbury.ac.nz/regulations/general-regulations/general-conditions-for-credit-regulations/](https://www.canterbury.ac.nz/regulations/general-regulations/general-conditions-for-credit-regulations/).

**Te Pīra Taumata | Reconsideration of Grades**
Students can appeal any decision made on their final grade, and should, in the first instance, speak to the course coordinator about their grade. Students can apply through Student Services to appeal for up to four weeks after the release of results: [https://www.canterbury.ac.nz/study/examinations/result-dates-and-appeals/](https://www.canterbury.ac.nz/study/examinations/result-dates-and-appeals/).

For more information see General Course and Examination Regulations in the University Calendar: [https://www.canterbury.ac.nz/publications/brochure-gallery/](https://www.canterbury.ac.nz/publications/brochure-gallery/)

**Ngā Ritenga Nawe | Complaints and Grievances**
If a student encounters any problems regarding any aspect of the course, they should in the first instance approach the lecturer concerned. Failing that, they can approach the course coordinator. For more information, please see the Psychology Handbook.

----------------------------------------------------------------------------------